#!/usr/bin/env npx tsx
/**
 * generate-catalog.ts — Validates stock tickers against Yahoo Finance
 * and outputs catalog TypeScript files.
 *
 * Usage:
 *   npx tsx scripts/generate-catalog.ts
 *
 * Reads CSV source data from scripts/data/ and validates each ticker
 * against Yahoo Finance. Outputs validated catalogs to:
 *   - packages/stocks/src/catalog-bmv.ts
 *   - packages/stocks/src/catalog-sic.ts
 *
 * Options:
 *   --dry-run     Print results without writing files
 *   --skip-validation  Skip Yahoo Finance validation (trust CSV data)
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface StockRow {
  symbol: string;
  yahooSymbol: string;
  name: string;
  sector: string;
  exchange: 'BMV' | 'SIC';
}

const DELAY_MS = 200; // Between Yahoo Finance requests
const dryRun = process.argv.includes('--dry-run');
const skipValidation = process.argv.includes('--skip-validation');

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

function parseCSV(filePath: string, exchange: 'BMV' | 'SIC'): StockRow[] {
  const content = readFileSync(filePath, 'utf-8');
  const lines = content.trim().split('\n');
  const rows: StockRow[] = [];

  for (let i = 1; i < lines.length; i++) { // Skip header
    const line = lines[i].trim();
    if (!line || line.startsWith('#')) continue;

    const [symbol, yahooSymbol, name, sector] = line.split(',').map((s) => s.trim());
    if (!symbol || !yahooSymbol || !name || !sector) {
      console.error(`[SKIP] Invalid CSV row ${i + 1}: ${line}`);
      continue;
    }
    rows.push({ symbol, yahooSymbol, name, sector, exchange });
  }

  return rows;
}

async function validateTicker(yahooSymbol: string): Promise<boolean> {
  try {
    const url = `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(yahooSymbol)}?range=1d&interval=1d`;
    const res = await fetch(url, {
      headers: { 'User-Agent': 'mx-market-tools/1.0' },
    });
    if (!res.ok) return false;
    const data = await res.json() as { chart?: { result?: unknown[] } };
    return !!(data?.chart?.result?.length);
  } catch {
    return false;
  }
}

function generateTS(stocks: StockRow[], exchange: 'BMV' | 'SIC'): string {
  const varName = exchange === 'BMV' ? 'BMV_STOCKS' : 'SIC_STOCKS';
  const desc = exchange === 'BMV'
    ? 'BMV (Bolsa Mexicana de Valores) domestic stock catalog.'
    : 'SIC (Sistema Internacional de Cotizaciones) international stock catalog.';

  let ts = `import type { BMVStock } from './types.js';\n\n`;
  ts += `/**\n * ${desc}\n * Auto-generated by scripts/generate-catalog.ts\n */\n`;
  ts += `export const ${varName}: BMVStock[] = [\n`;

  // Group by sector
  const bySector = new Map<string, StockRow[]>();
  for (const s of stocks) {
    const list = bySector.get(s.sector) ?? [];
    list.push(s);
    bySector.set(s.sector, list);
  }

  for (const [sector, entries] of bySector) {
    ts += `  // ── ${sector} ${'─'.repeat(Math.max(1, 70 - sector.length))}\n`;
    for (const s of entries) {
      const sym = `'${s.symbol}'`.padEnd(14);
      const yahoo = `'${s.yahooSymbol}'`.padEnd(18);
      const name = `'${s.name.replace(/'/g, "\\'")}'`.padEnd(50);
      ts += `  { symbol: ${sym} yahooSymbol: ${yahoo} name: ${name} exchange: '${exchange}', sector: '${s.sector}' },\n`;
    }
  }

  ts += `];\n`;
  return ts;
}

async function main() {
  const bmvCsvPath = resolve(__dirname, 'data/bmv-tickers.csv');
  const sicCsvPath = resolve(__dirname, 'data/sic-tickers.csv');

  let bmvRows: StockRow[];
  let sicRows: StockRow[];

  try {
    bmvRows = parseCSV(bmvCsvPath, 'BMV');
    sicRows = parseCSV(sicCsvPath, 'SIC');
  } catch (e) {
    console.error('Error reading CSV files:', e);
    console.error('Create scripts/data/bmv-tickers.csv and scripts/data/sic-tickers.csv first.');
    console.error('Columns: symbol,yahooSymbol,name,sector');
    process.exit(1);
  }

  console.log(`Loaded ${bmvRows.length} BMV tickers, ${sicRows.length} SIC tickers`);

  if (!skipValidation) {
    console.log('Validating against Yahoo Finance...');
    const allRows = [...bmvRows, ...sicRows];
    const failed: string[] = [];

    for (let i = 0; i < allRows.length; i++) {
      const row = allRows[i];
      process.stdout.write(`\r  [${i + 1}/${allRows.length}] ${row.yahooSymbol}...`);
      const ok = await validateTicker(row.yahooSymbol);
      if (!ok) {
        failed.push(`${row.exchange}:${row.symbol} (${row.yahooSymbol})`);
      }
      await sleep(DELAY_MS);
    }

    console.log(''); // newline after progress

    if (failed.length > 0) {
      console.error(`\n${failed.length} tickers failed validation:`);
      for (const f of failed) console.error(`  ✗ ${f}`);

      // Remove failed from rows
      const failedSymbols = new Set(failed.map((f) => f.split(' ')[0].split(':')[1]));
      bmvRows = bmvRows.filter((r) => !failedSymbols.has(r.symbol));
      sicRows = sicRows.filter((r) => !failedSymbols.has(r.symbol));
      console.log(`\nAfter filtering: ${bmvRows.length} BMV, ${sicRows.length} SIC`);
    } else {
      console.log('All tickers validated successfully!');
    }
  }

  const bmvTS = generateTS(bmvRows, 'BMV');
  const sicTS = generateTS(sicRows, 'SIC');

  if (dryRun) {
    console.log('\n--- catalog-bmv.ts ---');
    console.log(bmvTS.slice(0, 500) + '\n...');
    console.log(`\n--- catalog-sic.ts ---`);
    console.log(sicTS.slice(0, 500) + '\n...');
    console.log(`\nDry run complete. ${bmvRows.length} BMV + ${sicRows.length} SIC = ${bmvRows.length + sicRows.length} total`);
  } else {
    const bmvOut = resolve(__dirname, '../packages/stocks/src/catalog-bmv.ts');
    const sicOut = resolve(__dirname, '../packages/stocks/src/catalog-sic.ts');
    writeFileSync(bmvOut, bmvTS, 'utf-8');
    writeFileSync(sicOut, sicTS, 'utf-8');
    console.log(`\nWrote ${bmvRows.length} BMV stocks to ${bmvOut}`);
    console.log(`Wrote ${sicRows.length} SIC stocks to ${sicOut}`);
    console.log(`Total: ${bmvRows.length + sicRows.length} stocks`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
