import type { BMVStock } from './types.js';

/**
 * SIC (Sistema Internacional de Cotizaciones) stock catalog.
 * Foreign stocks available for trading on Mexico's BMV through the SIC system.
 * Yahoo Finance symbols use the .MX suffix for SIC-listed securities.
 */
export const SIC_STOCKS: BMVStock[] = [
  // ── Technology ────────────────────────────────────────────────────────────────
  { symbol: 'AAPL',       yahooSymbol: 'AAPL.MX',       name: 'Apple Inc.',                                   exchange: 'SIC', sector: 'Technology' },
  { symbol: 'MSFT',       yahooSymbol: 'MSFT.MX',       name: 'Microsoft Corporation',                        exchange: 'SIC', sector: 'Technology' },
  { symbol: 'GOOGL',      yahooSymbol: 'GOOGL.MX',      name: 'Alphabet Inc. (Google)',                       exchange: 'SIC', sector: 'Technology' },
  { symbol: 'GOOG',       yahooSymbol: 'GOOG.MX',       name: 'Alphabet Inc. Class C',                        exchange: 'SIC', sector: 'Technology' },
  { symbol: 'META',       yahooSymbol: 'META.MX',       name: 'Meta Platforms',                               exchange: 'SIC', sector: 'Technology' },
  { symbol: 'AMZN',       yahooSymbol: 'AMZN.MX',       name: 'Amazon.com Inc.',                              exchange: 'SIC', sector: 'Technology' },
  { symbol: 'NVDA',       yahooSymbol: 'NVDA.MX',       name: 'NVIDIA Corporation',                           exchange: 'SIC', sector: 'Technology' },
  { symbol: 'TSM',        yahooSymbol: 'TSM.MX',        name: 'Taiwan Semiconductor (TSMC)',                  exchange: 'SIC', sector: 'Technology' },
  { symbol: 'AVGO',       yahooSymbol: 'AVGO.MX',       name: 'Broadcom Inc.',                                exchange: 'SIC', sector: 'Technology' },
  { symbol: 'ORCL',       yahooSymbol: 'ORCL.MX',       name: 'Oracle Corporation',                           exchange: 'SIC', sector: 'Technology' },
  { symbol: 'CSCO',       yahooSymbol: 'CSCO.MX',       name: 'Cisco Systems',                                exchange: 'SIC', sector: 'Technology' },
  { symbol: 'CRM',        yahooSymbol: 'CRM.MX',        name: 'Salesforce Inc.',                              exchange: 'SIC', sector: 'Technology' },
  { symbol: 'ACN',        yahooSymbol: 'ACN.MX',        name: 'Accenture',                                    exchange: 'SIC', sector: 'Technology' },
  { symbol: 'ADBE',       yahooSymbol: 'ADBE.MX',       name: 'Adobe Inc.',                                   exchange: 'SIC', sector: 'Technology' },
  { symbol: 'AMD',        yahooSymbol: 'AMD.MX',        name: 'Advanced Micro Devices',                       exchange: 'SIC', sector: 'Technology' },
  { symbol: 'INTC',       yahooSymbol: 'INTC.MX',       name: 'Intel Corporation',                            exchange: 'SIC', sector: 'Technology' },
  { symbol: 'TXN',        yahooSymbol: 'TXN.MX',        name: 'Texas Instruments',                            exchange: 'SIC', sector: 'Technology' },
  { symbol: 'QCOM',       yahooSymbol: 'QCOM.MX',       name: 'Qualcomm Inc.',                                exchange: 'SIC', sector: 'Technology' },
  { symbol: 'INTU',       yahooSymbol: 'INTU.MX',       name: 'Intuit Inc.',                                  exchange: 'SIC', sector: 'Technology' },
  { symbol: 'AMAT',       yahooSymbol: 'AMAT.MX',       name: 'Applied Materials',                            exchange: 'SIC', sector: 'Technology' },
  { symbol: 'NOW',        yahooSymbol: 'NOW.MX',        name: 'ServiceNow Inc.',                              exchange: 'SIC', sector: 'Technology' },
  { symbol: 'IBM',        yahooSymbol: 'IBM.MX',        name: 'International Business Machines',              exchange: 'SIC', sector: 'Technology' },
  { symbol: 'MU',         yahooSymbol: 'MU.MX',         name: 'Micron Technology',                            exchange: 'SIC', sector: 'Technology' },
  { symbol: 'SNPS',       yahooSymbol: 'SNPS.MX',       name: 'Synopsys Inc.',                                exchange: 'SIC', sector: 'Technology' },
  { symbol: 'CDNS',       yahooSymbol: 'CDNS.MX',       name: 'Cadence Design Systems',                      exchange: 'SIC', sector: 'Technology' },
  { symbol: 'LRCX',       yahooSymbol: 'LRCX.MX',       name: 'Lam Research',                                 exchange: 'SIC', sector: 'Technology' },
  { symbol: 'KLAC',       yahooSymbol: 'KLAC.MX',       name: 'KLA Corporation',                              exchange: 'SIC', sector: 'Technology' },
  { symbol: 'NXPI',       yahooSymbol: 'NXPI.MX',       name: 'NXP Semiconductors',                           exchange: 'SIC', sector: 'Technology' },
  { symbol: 'MRVL',       yahooSymbol: 'MRVL.MX',       name: 'Marvell Technology',                           exchange: 'SIC', sector: 'Technology' },
  { symbol: 'PANW',       yahooSymbol: 'PANW.MX',       name: 'Palo Alto Networks',                           exchange: 'SIC', sector: 'Technology' },
  { symbol: 'CRWD',       yahooSymbol: 'CRWD.MX',       name: 'CrowdStrike Holdings',                        exchange: 'SIC', sector: 'Technology' },
  { symbol: 'FTNT',       yahooSymbol: 'FTNT.MX',       name: 'Fortinet Inc.',                                exchange: 'SIC', sector: 'Technology' },
  { symbol: 'PLTR',       yahooSymbol: 'PLTR.MX',       name: 'Palantir Technologies',                       exchange: 'SIC', sector: 'Technology' },
  { symbol: 'SHOP',       yahooSymbol: 'SHOP.MX',       name: 'Shopify Inc.',                                 exchange: 'SIC', sector: 'Technology' },
  { symbol: 'SNOW',       yahooSymbol: 'SNOW.MX',       name: 'Snowflake Inc.',                               exchange: 'SIC', sector: 'Technology' },
  { symbol: 'WDAY',       yahooSymbol: 'WDAY.MX',       name: 'Workday Inc.',                                 exchange: 'SIC', sector: 'Technology' },
  { symbol: 'NET',        yahooSymbol: 'NET.MX',        name: 'Cloudflare Inc.',                              exchange: 'SIC', sector: 'Technology' },
  { symbol: 'DDOG',       yahooSymbol: 'DDOG.MX',       name: 'Datadog Inc.',                                 exchange: 'SIC', sector: 'Technology' },
  { symbol: 'ZS',         yahooSymbol: 'ZS.MX',         name: 'Zscaler Inc.',                                 exchange: 'SIC', sector: 'Technology' },
  { symbol: 'MCHP',       yahooSymbol: 'MCHP.MX',       name: 'Microchip Technology',                         exchange: 'SIC', sector: 'Technology' },
  { symbol: 'ON',         yahooSymbol: 'ON.MX',         name: 'ON Semiconductor',                             exchange: 'SIC', sector: 'Technology' },
  { symbol: 'HPE',        yahooSymbol: 'HPE.MX',        name: 'Hewlett Packard Enterprise',                   exchange: 'SIC', sector: 'Technology' },
  { symbol: 'HPQ',        yahooSymbol: 'HPQ.MX',        name: 'HP Inc.',                                      exchange: 'SIC', sector: 'Technology' },
  { symbol: 'DELL',       yahooSymbol: 'DELL.MX',       name: 'Dell Technologies',                            exchange: 'SIC', sector: 'Technology' },
  { symbol: 'UBER',       yahooSymbol: 'UBER.MX',       name: 'Uber Technologies',                            exchange: 'SIC', sector: 'Technology' },
  { symbol: 'ARM',        yahooSymbol: 'ARM.MX',        name: 'Arm Holdings',                                 exchange: 'SIC', sector: 'Technology' },

  // ── Software / Internet ───────────────────────────────────────────────────────
  { symbol: 'NFLX',       yahooSymbol: 'NFLX.MX',       name: 'Netflix Inc.',                                 exchange: 'SIC', sector: 'Software' },
  { symbol: 'SPOT',       yahooSymbol: 'SPOT.MX',       name: 'Spotify Technology',                           exchange: 'SIC', sector: 'Software' },
  { symbol: 'SQ',         yahooSymbol: 'SQ.MX',         name: 'Block Inc. (Square)',                          exchange: 'SIC', sector: 'Software' },
  { symbol: 'PYPL',       yahooSymbol: 'PYPL.MX',       name: 'PayPal Holdings',                              exchange: 'SIC', sector: 'Software' },
  { symbol: 'COIN',       yahooSymbol: 'COIN.MX',       name: 'Coinbase Global',                              exchange: 'SIC', sector: 'Software' },
  { symbol: 'ABNB',       yahooSymbol: 'ABNB.MX',       name: 'Airbnb Inc.',                                  exchange: 'SIC', sector: 'Software' },
  { symbol: 'SNAP',       yahooSymbol: 'SNAP.MX',       name: 'Snap Inc.',                                    exchange: 'SIC', sector: 'Software' },
  { symbol: 'PINS',       yahooSymbol: 'PINS.MX',       name: 'Pinterest Inc.',                               exchange: 'SIC', sector: 'Software' },
  { symbol: 'RBLX',       yahooSymbol: 'RBLX.MX',       name: 'Roblox Corporation',                           exchange: 'SIC', sector: 'Software' },
  { symbol: 'U',          yahooSymbol: 'U.MX',          name: 'Unity Software',                               exchange: 'SIC', sector: 'Software' },
  { symbol: 'ROKU',       yahooSymbol: 'ROKU.MX',       name: 'Roku Inc.',                                    exchange: 'SIC', sector: 'Software' },
  { symbol: 'TWLO',       yahooSymbol: 'TWLO.MX',       name: 'Twilio Inc.',                                  exchange: 'SIC', sector: 'Software' },
  { symbol: 'TEAM',       yahooSymbol: 'TEAM.MX',       name: 'Atlassian Corporation',                        exchange: 'SIC', sector: 'Software' },
  { symbol: 'HUBS',       yahooSymbol: 'HUBS.MX',       name: 'HubSpot Inc.',                                 exchange: 'SIC', sector: 'Software' },
  { symbol: 'TTD',        yahooSymbol: 'TTD.MX',        name: 'The Trade Desk',                               exchange: 'SIC', sector: 'Software' },
  { symbol: 'DOCU',       yahooSymbol: 'DOCU.MX',       name: 'DocuSign Inc.',                                exchange: 'SIC', sector: 'Software' },
  { symbol: 'ZM',         yahooSymbol: 'ZM.MX',         name: 'Zoom Video Communications',                   exchange: 'SIC', sector: 'Software' },
  { symbol: 'OKTA',       yahooSymbol: 'OKTA.MX',       name: 'Okta Inc.',                                    exchange: 'SIC', sector: 'Software' },
  { symbol: 'MDB',        yahooSymbol: 'MDB.MX',        name: 'MongoDB Inc.',                                 exchange: 'SIC', sector: 'Software' },
  { symbol: 'VEEV',       yahooSymbol: 'VEEV.MX',       name: 'Veeva Systems',                                exchange: 'SIC', sector: 'Software' },
  { symbol: 'BILL',       yahooSymbol: 'BILL.MX',       name: 'BILL Holdings',                                exchange: 'SIC', sector: 'Software' },

  // ── E-Commerce / Retail ───────────────────────────────────────────────────────
  { symbol: 'BABA',       yahooSymbol: 'BABA.MX',       name: 'Alibaba Group',                                exchange: 'SIC', sector: 'E-Commerce' },
  { symbol: 'JD',         yahooSymbol: 'JD.MX',         name: 'JD.com Inc.',                                  exchange: 'SIC', sector: 'E-Commerce' },
  { symbol: 'PDD',        yahooSymbol: 'PDD.MX',        name: 'PDD Holdings (Pinduoduo)',                     exchange: 'SIC', sector: 'E-Commerce' },
  { symbol: 'MELI',       yahooSymbol: 'MELI.MX',       name: 'MercadoLibre Inc.',                            exchange: 'SIC', sector: 'E-Commerce' },
  { symbol: 'SE',         yahooSymbol: 'SE.MX',         name: 'Sea Limited',                                  exchange: 'SIC', sector: 'E-Commerce' },
  { symbol: 'EBAY',       yahooSymbol: 'EBAY.MX',       name: 'eBay Inc.',                                    exchange: 'SIC', sector: 'E-Commerce' },
  { symbol: 'ETSY',       yahooSymbol: 'ETSY.MX',       name: 'Etsy Inc.',                                    exchange: 'SIC', sector: 'E-Commerce' },

  // ── Retail (Physical) ─────────────────────────────────────────────────────────
  { symbol: 'WMT',        yahooSymbol: 'WMT.MX',        name: 'Walmart Inc.',                                 exchange: 'SIC', sector: 'Retail' },
  { symbol: 'COST',       yahooSymbol: 'COST.MX',       name: 'Costco Wholesale',                             exchange: 'SIC', sector: 'Retail' },
  { symbol: 'HD',         yahooSymbol: 'HD.MX',         name: 'The Home Depot',                               exchange: 'SIC', sector: 'Retail' },
  { symbol: 'LOW',        yahooSymbol: 'LOW.MX',        name: 'Lowe\'s Companies',                            exchange: 'SIC', sector: 'Retail' },
  { symbol: 'TGT',        yahooSymbol: 'TGT.MX',        name: 'Target Corporation',                           exchange: 'SIC', sector: 'Retail' },
  { symbol: 'TJX',        yahooSymbol: 'TJX.MX',        name: 'TJX Companies',                                exchange: 'SIC', sector: 'Retail' },
  { symbol: 'ROST',       yahooSymbol: 'ROST.MX',       name: 'Ross Stores',                                  exchange: 'SIC', sector: 'Retail' },
  { symbol: 'DG',         yahooSymbol: 'DG.MX',         name: 'Dollar General',                               exchange: 'SIC', sector: 'Retail' },
  { symbol: 'DLTR',       yahooSymbol: 'DLTR.MX',       name: 'Dollar Tree',                                  exchange: 'SIC', sector: 'Retail' },

  // ── Financial Services ────────────────────────────────────────────────────────
  { symbol: 'JPM',        yahooSymbol: 'JPM.MX',        name: 'JPMorgan Chase & Co.',                         exchange: 'SIC', sector: 'Financial' },
  { symbol: 'BAC',        yahooSymbol: 'BAC.MX',        name: 'Bank of America',                              exchange: 'SIC', sector: 'Financial' },
  { symbol: 'WFC',        yahooSymbol: 'WFC.MX',        name: 'Wells Fargo & Co.',                            exchange: 'SIC', sector: 'Financial' },
  { symbol: 'GS',         yahooSymbol: 'GS.MX',         name: 'Goldman Sachs Group',                          exchange: 'SIC', sector: 'Financial' },
  { symbol: 'MS',         yahooSymbol: 'MS.MX',         name: 'Morgan Stanley',                               exchange: 'SIC', sector: 'Financial' },
  { symbol: 'C',          yahooSymbol: 'C.MX',          name: 'Citigroup Inc.',                               exchange: 'SIC', sector: 'Financial' },
  { symbol: 'BLK',        yahooSymbol: 'BLK.MX',        name: 'BlackRock Inc.',                                exchange: 'SIC', sector: 'Financial' },
  { symbol: 'SCHW',       yahooSymbol: 'SCHW.MX',       name: 'Charles Schwab',                               exchange: 'SIC', sector: 'Financial' },
  { symbol: 'AXP',        yahooSymbol: 'AXP.MX',        name: 'American Express',                             exchange: 'SIC', sector: 'Financial' },
  { symbol: 'V',          yahooSymbol: 'V.MX',          name: 'Visa Inc.',                                    exchange: 'SIC', sector: 'Financial' },
  { symbol: 'MA',         yahooSymbol: 'MA.MX',         name: 'Mastercard Inc.',                              exchange: 'SIC', sector: 'Financial' },
  { symbol: 'COF',        yahooSymbol: 'COF.MX',        name: 'Capital One Financial',                        exchange: 'SIC', sector: 'Financial' },
  { symbol: 'USB',        yahooSymbol: 'USB.MX',        name: 'U.S. Bancorp',                                 exchange: 'SIC', sector: 'Financial' },
  { symbol: 'PNC',        yahooSymbol: 'PNC.MX',        name: 'PNC Financial Services',                       exchange: 'SIC', sector: 'Financial' },
  { symbol: 'TFC',        yahooSymbol: 'TFC.MX',        name: 'Truist Financial',                             exchange: 'SIC', sector: 'Financial' },
  { symbol: 'CME',        yahooSymbol: 'CME.MX',        name: 'CME Group',                                    exchange: 'SIC', sector: 'Financial' },
  { symbol: 'ICE',        yahooSymbol: 'ICE.MX',        name: 'Intercontinental Exchange',                    exchange: 'SIC', sector: 'Financial' },
  { symbol: 'SPGI',       yahooSymbol: 'SPGI.MX',       name: 'S&P Global',                                   exchange: 'SIC', sector: 'Financial' },
  { symbol: 'MCO',        yahooSymbol: 'MCO.MX',        name: 'Moody\'s Corporation',                         exchange: 'SIC', sector: 'Financial' },
  { symbol: 'MMC',        yahooSymbol: 'MMC.MX',        name: 'Marsh & McLennan',                             exchange: 'SIC', sector: 'Financial' },
  { symbol: 'AON',        yahooSymbol: 'AON.MX',        name: 'Aon plc',                                     exchange: 'SIC', sector: 'Financial' },
  { symbol: 'FI',         yahooSymbol: 'FI.MX',         name: 'Fiserv Inc.',                                  exchange: 'SIC', sector: 'Financial' },
  { symbol: 'FIS',        yahooSymbol: 'FIS.MX',        name: 'Fidelity National Information Services',       exchange: 'SIC', sector: 'Financial' },

  // ── Insurance ─────────────────────────────────────────────────────────────────
  { symbol: 'BRK-B',      yahooSymbol: 'BRK-B.MX',      name: 'Berkshire Hathaway Class B',                   exchange: 'SIC', sector: 'Insurance' },
  { symbol: 'PGR',        yahooSymbol: 'PGR.MX',        name: 'Progressive Corporation',                      exchange: 'SIC', sector: 'Insurance' },
  { symbol: 'CB',         yahooSymbol: 'CB.MX',         name: 'Chubb Limited',                                exchange: 'SIC', sector: 'Insurance' },
  { symbol: 'MET',        yahooSymbol: 'MET.MX',        name: 'MetLife Inc.',                                 exchange: 'SIC', sector: 'Insurance' },
  { symbol: 'AIG',        yahooSymbol: 'AIG.MX',        name: 'American International Group',                 exchange: 'SIC', sector: 'Insurance' },
  { symbol: 'ALL',        yahooSymbol: 'ALL.MX',        name: 'Allstate Corporation',                         exchange: 'SIC', sector: 'Insurance' },

  // ── Healthcare / Pharma ───────────────────────────────────────────────────────
  { symbol: 'JNJ',        yahooSymbol: 'JNJ.MX',        name: 'Johnson & Johnson',                            exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'UNH',        yahooSymbol: 'UNH.MX',        name: 'UnitedHealth Group',                           exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'LLY',        yahooSymbol: 'LLY.MX',        name: 'Eli Lilly and Company',                        exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'ABBV',       yahooSymbol: 'ABBV.MX',       name: 'AbbVie Inc.',                                  exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'MRK',        yahooSymbol: 'MRK.MX',        name: 'Merck & Co.',                                  exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'PFE',        yahooSymbol: 'PFE.MX',        name: 'Pfizer Inc.',                                  exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'TMO',        yahooSymbol: 'TMO.MX',        name: 'Thermo Fisher Scientific',                    exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'ABT',        yahooSymbol: 'ABT.MX',        name: 'Abbott Laboratories',                          exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'DHR',        yahooSymbol: 'DHR.MX',        name: 'Danaher Corporation',                          exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'BMY',        yahooSymbol: 'BMY.MX',        name: 'Bristol-Myers Squibb',                         exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'AMGN',       yahooSymbol: 'AMGN.MX',       name: 'Amgen Inc.',                                   exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'GILD',       yahooSymbol: 'GILD.MX',       name: 'Gilead Sciences',                              exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'VRTX',       yahooSymbol: 'VRTX.MX',       name: 'Vertex Pharmaceuticals',                      exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'ISRG',       yahooSymbol: 'ISRG.MX',       name: 'Intuitive Surgical',                           exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'REGN',       yahooSymbol: 'REGN.MX',       name: 'Regeneron Pharmaceuticals',                   exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'SYK',        yahooSymbol: 'SYK.MX',        name: 'Stryker Corporation',                          exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'BDX',        yahooSymbol: 'BDX.MX',        name: 'Becton Dickinson',                             exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'MDT',        yahooSymbol: 'MDT.MX',        name: 'Medtronic plc',                                exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'ZTS',        yahooSymbol: 'ZTS.MX',        name: 'Zoetis Inc.',                                  exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'MRNA',       yahooSymbol: 'MRNA.MX',       name: 'Moderna Inc.',                                 exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'BIIB',       yahooSymbol: 'BIIB.MX',       name: 'Biogen Inc.',                                  exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'DXCM',       yahooSymbol: 'DXCM.MX',       name: 'DexCom Inc.',                                  exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'EW',         yahooSymbol: 'EW.MX',         name: 'Edwards Lifesciences',                        exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'A',          yahooSymbol: 'A.MX',          name: 'Agilent Technologies',                        exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'IQV',        yahooSymbol: 'IQV.MX',        name: 'IQVIA Holdings',                               exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'CI',         yahooSymbol: 'CI.MX',         name: 'The Cigna Group',                              exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'ELV',        yahooSymbol: 'ELV.MX',        name: 'Elevance Health',                              exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'HCA',        yahooSymbol: 'HCA.MX',        name: 'HCA Healthcare',                               exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'CVS',        yahooSymbol: 'CVS.MX',        name: 'CVS Health',                                   exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'NVO',        yahooSymbol: 'NVO.MX',        name: 'Novo Nordisk',                                 exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'AZN',        yahooSymbol: 'AZN.MX',        name: 'AstraZeneca',                                  exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'SNY',        yahooSymbol: 'SNY.MX',        name: 'Sanofi',                                       exchange: 'SIC', sector: 'Healthcare' },
  { symbol: 'GSK',        yahooSymbol: 'GSK.MX',        name: 'GSK plc',                                     exchange: 'SIC', sector: 'Healthcare' },

  // ── Consumer Staples ──────────────────────────────────────────────────────────
  { symbol: 'PG',         yahooSymbol: 'PG.MX',         name: 'Procter & Gamble',                             exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'KO',         yahooSymbol: 'KO.MX',         name: 'Coca-Cola Company',                            exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'PEP',        yahooSymbol: 'PEP.MX',        name: 'PepsiCo Inc.',                                 exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'PM',         yahooSymbol: 'PM.MX',         name: 'Philip Morris International',                  exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'MO',         yahooSymbol: 'MO.MX',         name: 'Altria Group',                                 exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'MDLZ',       yahooSymbol: 'MDLZ.MX',       name: 'Mondelez International',                      exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'CL',         yahooSymbol: 'CL.MX',         name: 'Colgate-Palmolive',                            exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'KMB',        yahooSymbol: 'KMB.MX',        name: 'Kimberly-Clark',                               exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'EL',         yahooSymbol: 'EL.MX',         name: 'Estée Lauder',                                 exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'KHC',        yahooSymbol: 'KHC.MX',        name: 'Kraft Heinz',                                  exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'GIS',        yahooSymbol: 'GIS.MX',        name: 'General Mills',                                exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'K',          yahooSymbol: 'K.MX',          name: 'Kellanova',                                    exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'HSY',        yahooSymbol: 'HSY.MX',        name: 'Hershey Company',                              exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'STZ',        yahooSymbol: 'STZ.MX',        name: 'Constellation Brands',                         exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'SJM',        yahooSymbol: 'SJM.MX',        name: 'J.M. Smucker',                                 exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'CAG',        yahooSymbol: 'CAG.MX',        name: 'Conagra Brands',                               exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'UL',         yahooSymbol: 'UL.MX',         name: 'Unilever',                                     exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'DEO',        yahooSymbol: 'DEO.MX',        name: 'Diageo',                                       exchange: 'SIC', sector: 'Consumer Staples' },
  { symbol: 'BUD',        yahooSymbol: 'BUD.MX',        name: 'Anheuser-Busch InBev',                         exchange: 'SIC', sector: 'Consumer Staples' },

  // ── Consumer Discretionary ────────────────────────────────────────────────────
  { symbol: 'TSLA',       yahooSymbol: 'TSLA.MX',       name: 'Tesla Inc.',                                   exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'NKE',        yahooSymbol: 'NKE.MX',        name: 'NIKE Inc.',                                    exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'SBUX',       yahooSymbol: 'SBUX.MX',       name: 'Starbucks Corporation',                        exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'MCD',        yahooSymbol: 'MCD.MX',        name: 'McDonald\'s Corporation',                      exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'DIS',        yahooSymbol: 'DIS.MX',        name: 'Walt Disney Company',                          exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'BKNG',       yahooSymbol: 'BKNG.MX',       name: 'Booking Holdings',                             exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'LULU',       yahooSymbol: 'LULU.MX',       name: 'Lululemon Athletica',                          exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'ORLY',       yahooSymbol: 'ORLY.MX',       name: 'O\'Reilly Automotive',                         exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'AZO',        yahooSymbol: 'AZO.MX',        name: 'AutoZone Inc.',                                exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'GM',         yahooSymbol: 'GM.MX',         name: 'General Motors',                               exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'F',          yahooSymbol: 'F.MX',          name: 'Ford Motor Company',                           exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'RIVN',       yahooSymbol: 'RIVN.MX',       name: 'Rivian Automotive',                            exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'CMG',        yahooSymbol: 'CMG.MX',        name: 'Chipotle Mexican Grill',                      exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'YUM',        yahooSymbol: 'YUM.MX',        name: 'Yum! Brands',                                  exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'MAR',        yahooSymbol: 'MAR.MX',        name: 'Marriott International',                      exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'HLT',        yahooSymbol: 'HLT.MX',        name: 'Hilton Worldwide',                             exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'RCL',        yahooSymbol: 'RCL.MX',        name: 'Royal Caribbean Cruises',                      exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'LVS',        yahooSymbol: 'LVS.MX',        name: 'Las Vegas Sands',                              exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'DHI',        yahooSymbol: 'DHI.MX',        name: 'D.R. Horton',                                  exchange: 'SIC', sector: 'Consumer Discretionary' },
  { symbol: 'LEN',        yahooSymbol: 'LEN.MX',        name: 'Lennar Corporation',                           exchange: 'SIC', sector: 'Consumer Discretionary' },

  // ── Energy ────────────────────────────────────────────────────────────────────
  { symbol: 'XOM',        yahooSymbol: 'XOM.MX',        name: 'Exxon Mobil',                                  exchange: 'SIC', sector: 'Energy' },
  { symbol: 'CVX',        yahooSymbol: 'CVX.MX',        name: 'Chevron Corporation',                          exchange: 'SIC', sector: 'Energy' },
  { symbol: 'COP',        yahooSymbol: 'COP.MX',        name: 'ConocoPhillips',                               exchange: 'SIC', sector: 'Energy' },
  { symbol: 'SLB',        yahooSymbol: 'SLB.MX',        name: 'Schlumberger',                                 exchange: 'SIC', sector: 'Energy' },
  { symbol: 'EOG',        yahooSymbol: 'EOG.MX',        name: 'EOG Resources',                                exchange: 'SIC', sector: 'Energy' },
  { symbol: 'MPC',        yahooSymbol: 'MPC.MX',        name: 'Marathon Petroleum',                           exchange: 'SIC', sector: 'Energy' },
  { symbol: 'PSX',        yahooSymbol: 'PSX.MX',        name: 'Phillips 66',                                  exchange: 'SIC', sector: 'Energy' },
  { symbol: 'VLO',        yahooSymbol: 'VLO.MX',        name: 'Valero Energy',                                exchange: 'SIC', sector: 'Energy' },
  { symbol: 'OXY',        yahooSymbol: 'OXY.MX',        name: 'Occidental Petroleum',                         exchange: 'SIC', sector: 'Energy' },
  { symbol: 'HAL',        yahooSymbol: 'HAL.MX',        name: 'Halliburton Company',                          exchange: 'SIC', sector: 'Energy' },
  { symbol: 'KMI',        yahooSymbol: 'KMI.MX',        name: 'Kinder Morgan',                                exchange: 'SIC', sector: 'Energy' },
  { symbol: 'WMB',        yahooSymbol: 'WMB.MX',        name: 'Williams Companies',                           exchange: 'SIC', sector: 'Energy' },
  { symbol: 'ENB',        yahooSymbol: 'ENB.MX',        name: 'Enbridge Inc.',                                exchange: 'SIC', sector: 'Energy' },
  { symbol: 'BP',         yahooSymbol: 'BP.MX',         name: 'BP plc',                                      exchange: 'SIC', sector: 'Energy' },
  { symbol: 'SHEL',       yahooSymbol: 'SHEL.MX',       name: 'Shell plc',                                   exchange: 'SIC', sector: 'Energy' },
  { symbol: 'TTE',        yahooSymbol: 'TTE.MX',        name: 'TotalEnergies',                                exchange: 'SIC', sector: 'Energy' },
  { symbol: 'EQNR',       yahooSymbol: 'EQNR.MX',       name: 'Equinor ASA',                                  exchange: 'SIC', sector: 'Energy' },

  // ── Industrial ────────────────────────────────────────────────────────────────
  { symbol: 'CAT',        yahooSymbol: 'CAT.MX',        name: 'Caterpillar Inc.',                             exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'DE',         yahooSymbol: 'DE.MX',         name: 'Deere & Company',                              exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'UNP',        yahooSymbol: 'UNP.MX',        name: 'Union Pacific',                                exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'HON',        yahooSymbol: 'HON.MX',        name: 'Honeywell International',                     exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'UPS',        yahooSymbol: 'UPS.MX',        name: 'United Parcel Service',                        exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'RTX',        yahooSymbol: 'RTX.MX',        name: 'RTX Corporation (Raytheon)',                   exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'BA',         yahooSymbol: 'BA.MX',         name: 'Boeing Company',                               exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'LMT',        yahooSymbol: 'LMT.MX',        name: 'Lockheed Martin',                              exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'GE',         yahooSymbol: 'GE.MX',         name: 'GE Aerospace',                                 exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'MMM',        yahooSymbol: 'MMM.MX',        name: '3M Company',                                   exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'GD',         yahooSymbol: 'GD.MX',         name: 'General Dynamics',                             exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'NOC',        yahooSymbol: 'NOC.MX',        name: 'Northrop Grumman',                             exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'EMR',        yahooSymbol: 'EMR.MX',        name: 'Emerson Electric',                             exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'ITW',        yahooSymbol: 'ITW.MX',        name: 'Illinois Tool Works',                          exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'WM',         yahooSymbol: 'WM.MX',         name: 'Waste Management',                             exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'ETN',        yahooSymbol: 'ETN.MX',        name: 'Eaton Corporation',                            exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'FDX',        yahooSymbol: 'FDX.MX',        name: 'FedEx Corporation',                            exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'CSX',        yahooSymbol: 'CSX.MX',        name: 'CSX Corporation',                              exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'NSC',        yahooSymbol: 'NSC.MX',        name: 'Norfolk Southern',                             exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'JCI',        yahooSymbol: 'JCI.MX',        name: 'Johnson Controls',                             exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'PH',         yahooSymbol: 'PH.MX',         name: 'Parker-Hannifin',                              exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'ROK',        yahooSymbol: 'ROK.MX',        name: 'Rockwell Automation',                          exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'CMI',        yahooSymbol: 'CMI.MX',        name: 'Cummins Inc.',                                 exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'CARR',       yahooSymbol: 'CARR.MX',       name: 'Carrier Global',                               exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'OTIS',       yahooSymbol: 'OTIS.MX',       name: 'Otis Worldwide',                               exchange: 'SIC', sector: 'Industrial' },

  // ── Materials ─────────────────────────────────────────────────────────────────
  { symbol: 'LIN',        yahooSymbol: 'LIN.MX',        name: 'Linde plc',                                   exchange: 'SIC', sector: 'Materials' },
  { symbol: 'SHW',        yahooSymbol: 'SHW.MX',        name: 'Sherwin-Williams',                             exchange: 'SIC', sector: 'Materials' },
  { symbol: 'APD',        yahooSymbol: 'APD.MX',        name: 'Air Products & Chemicals',                    exchange: 'SIC', sector: 'Materials' },
  { symbol: 'ECL',        yahooSymbol: 'ECL.MX',        name: 'Ecolab Inc.',                                  exchange: 'SIC', sector: 'Materials' },
  { symbol: 'FCX',        yahooSymbol: 'FCX.MX',        name: 'Freeport-McMoRan',                             exchange: 'SIC', sector: 'Materials' },
  { symbol: 'NEM',        yahooSymbol: 'NEM.MX',        name: 'Newmont Corporation',                          exchange: 'SIC', sector: 'Materials' },
  { symbol: 'DOW',        yahooSymbol: 'DOW.MX',        name: 'Dow Inc.',                                     exchange: 'SIC', sector: 'Materials' },
  { symbol: 'DD',         yahooSymbol: 'DD.MX',         name: 'DuPont de Nemours',                            exchange: 'SIC', sector: 'Materials' },
  { symbol: 'NUE',        yahooSymbol: 'NUE.MX',        name: 'Nucor Corporation',                            exchange: 'SIC', sector: 'Materials' },
  { symbol: 'VMC',        yahooSymbol: 'VMC.MX',        name: 'Vulcan Materials',                             exchange: 'SIC', sector: 'Materials' },
  { symbol: 'MLM',        yahooSymbol: 'MLM.MX',        name: 'Martin Marietta Materials',                   exchange: 'SIC', sector: 'Materials' },
  { symbol: 'VALE',       yahooSymbol: 'VALE.MX',       name: 'Vale S.A.',                                    exchange: 'SIC', sector: 'Materials' },
  { symbol: 'RIO',        yahooSymbol: 'RIO.MX',        name: 'Rio Tinto',                                    exchange: 'SIC', sector: 'Materials' },
  { symbol: 'BHP',        yahooSymbol: 'BHP.MX',        name: 'BHP Group',                                    exchange: 'SIC', sector: 'Materials' },

  // ── Utilities ─────────────────────────────────────────────────────────────────
  { symbol: 'NEE',        yahooSymbol: 'NEE.MX',        name: 'NextEra Energy',                               exchange: 'SIC', sector: 'Utilities' },
  { symbol: 'DUK',        yahooSymbol: 'DUK.MX',        name: 'Duke Energy',                                  exchange: 'SIC', sector: 'Utilities' },
  { symbol: 'SO',         yahooSymbol: 'SO.MX',         name: 'Southern Company',                             exchange: 'SIC', sector: 'Utilities' },
  { symbol: 'D',          yahooSymbol: 'D.MX',          name: 'Dominion Energy',                              exchange: 'SIC', sector: 'Utilities' },
  { symbol: 'AEP',        yahooSymbol: 'AEP.MX',        name: 'American Electric Power',                     exchange: 'SIC', sector: 'Utilities' },
  { symbol: 'SRE',        yahooSymbol: 'SRE.MX',        name: 'Sempra',                                       exchange: 'SIC', sector: 'Utilities' },
  { symbol: 'XEL',        yahooSymbol: 'XEL.MX',        name: 'Xcel Energy',                                  exchange: 'SIC', sector: 'Utilities' },
  { symbol: 'ED',         yahooSymbol: 'ED.MX',         name: 'Consolidated Edison',                          exchange: 'SIC', sector: 'Utilities' },
  { symbol: 'EXC',        yahooSymbol: 'EXC.MX',        name: 'Exelon Corporation',                           exchange: 'SIC', sector: 'Utilities' },
  { symbol: 'AWK',        yahooSymbol: 'AWK.MX',        name: 'American Water Works',                        exchange: 'SIC', sector: 'Utilities' },

  // ── Real Estate / REITs ───────────────────────────────────────────────────────
  { symbol: 'PLD',        yahooSymbol: 'PLD.MX',        name: 'Prologis Inc.',                                exchange: 'SIC', sector: 'REIT' },
  { symbol: 'AMT',        yahooSymbol: 'AMT.MX',        name: 'American Tower',                               exchange: 'SIC', sector: 'REIT' },
  { symbol: 'CCI',        yahooSymbol: 'CCI.MX',        name: 'Crown Castle',                                 exchange: 'SIC', sector: 'REIT' },
  { symbol: 'EQIX',       yahooSymbol: 'EQIX.MX',       name: 'Equinix Inc.',                                 exchange: 'SIC', sector: 'REIT' },
  { symbol: 'SPG',        yahooSymbol: 'SPG.MX',        name: 'Simon Property Group',                        exchange: 'SIC', sector: 'REIT' },
  { symbol: 'PSA',        yahooSymbol: 'PSA.MX',        name: 'Public Storage',                               exchange: 'SIC', sector: 'REIT' },
  { symbol: 'O',          yahooSymbol: 'O.MX',          name: 'Realty Income',                                exchange: 'SIC', sector: 'REIT' },
  { symbol: 'DLR',        yahooSymbol: 'DLR.MX',        name: 'Digital Realty Trust',                         exchange: 'SIC', sector: 'REIT' },
  { symbol: 'WELL',       yahooSymbol: 'WELL.MX',       name: 'Welltower Inc.',                               exchange: 'SIC', sector: 'REIT' },
  { symbol: 'AVB',        yahooSymbol: 'AVB.MX',        name: 'AvalonBay Communities',                        exchange: 'SIC', sector: 'REIT' },

  // ── Telecom ───────────────────────────────────────────────────────────────────
  { symbol: 'T',          yahooSymbol: 'T.MX',          name: 'AT&T Inc.',                                    exchange: 'SIC', sector: 'Telecom' },
  { symbol: 'VZ',         yahooSymbol: 'VZ.MX',         name: 'Verizon Communications',                      exchange: 'SIC', sector: 'Telecom' },
  { symbol: 'TMUS',       yahooSymbol: 'TMUS.MX',       name: 'T-Mobile US',                                  exchange: 'SIC', sector: 'Telecom' },
  { symbol: 'CMCSA',      yahooSymbol: 'CMCSA.MX',      name: 'Comcast Corporation',                          exchange: 'SIC', sector: 'Telecom' },
  { symbol: 'CHTR',       yahooSymbol: 'CHTR.MX',       name: 'Charter Communications',                      exchange: 'SIC', sector: 'Telecom' },

  // ── Media / Entertainment ─────────────────────────────────────────────────────
  { symbol: 'WBD',        yahooSymbol: 'WBD.MX',        name: 'Warner Bros. Discovery',                      exchange: 'SIC', sector: 'Media' },
  { symbol: 'PARA',       yahooSymbol: 'PARA.MX',       name: 'Paramount Global',                             exchange: 'SIC', sector: 'Media' },
  { symbol: 'EA',         yahooSymbol: 'EA.MX',         name: 'Electronic Arts',                              exchange: 'SIC', sector: 'Media' },
  { symbol: 'TTWO',       yahooSymbol: 'TTWO.MX',       name: 'Take-Two Interactive',                         exchange: 'SIC', sector: 'Media' },
  { symbol: 'SONY',       yahooSymbol: 'SONY.MX',       name: 'Sony Group',                                   exchange: 'SIC', sector: 'Media' },
  { symbol: 'NTDOY',      yahooSymbol: 'NTDOY.MX',      name: 'Nintendo Co.',                                 exchange: 'SIC', sector: 'Media' },

  // ── Aerospace / Defense ───────────────────────────────────────────────────────
  { symbol: 'LHX',        yahooSymbol: 'LHX.MX',        name: 'L3Harris Technologies',                       exchange: 'SIC', sector: 'Aerospace' },
  { symbol: 'TDG',        yahooSymbol: 'TDG.MX',        name: 'TransDigm Group',                              exchange: 'SIC', sector: 'Aerospace' },
  { symbol: 'HWM',        yahooSymbol: 'HWM.MX',        name: 'Howmet Aerospace',                             exchange: 'SIC', sector: 'Aerospace' },
  { symbol: 'HEI',        yahooSymbol: 'HEI.MX',        name: 'HEICO Corporation',                            exchange: 'SIC', sector: 'Aerospace' },

  // ── Automotive ────────────────────────────────────────────────────────────────
  { symbol: 'TM',         yahooSymbol: 'TM.MX',         name: 'Toyota Motor',                                 exchange: 'SIC', sector: 'Automotive' },
  { symbol: 'HMC',        yahooSymbol: 'HMC.MX',        name: 'Honda Motor Co.',                              exchange: 'SIC', sector: 'Automotive' },
  { symbol: 'STLA',       yahooSymbol: 'STLA.MX',       name: 'Stellantis N.V.',                              exchange: 'SIC', sector: 'Automotive' },
  { symbol: 'LI',         yahooSymbol: 'LI.MX',         name: 'Li Auto Inc.',                                 exchange: 'SIC', sector: 'Automotive' },
  { symbol: 'NIO',        yahooSymbol: 'NIO.MX',        name: 'NIO Inc.',                                     exchange: 'SIC', sector: 'Automotive' },
  { symbol: 'XPEV',       yahooSymbol: 'XPEV.MX',       name: 'XPeng Inc.',                                   exchange: 'SIC', sector: 'Automotive' },

  // ── Airlines / Transport ──────────────────────────────────────────────────────
  { symbol: 'DAL',        yahooSymbol: 'DAL.MX',        name: 'Delta Air Lines',                              exchange: 'SIC', sector: 'Airlines' },
  { symbol: 'UAL',        yahooSymbol: 'UAL.MX',        name: 'United Airlines Holdings',                    exchange: 'SIC', sector: 'Airlines' },
  { symbol: 'LUV',        yahooSymbol: 'LUV.MX',        name: 'Southwest Airlines',                           exchange: 'SIC', sector: 'Airlines' },
  { symbol: 'AAL',        yahooSymbol: 'AAL.MX',        name: 'American Airlines Group',                     exchange: 'SIC', sector: 'Airlines' },

  // ── LatAm ─────────────────────────────────────────────────────────────────────
  { symbol: 'NU',         yahooSymbol: 'NU.MX',         name: 'Nu Holdings (Nubank)',                         exchange: 'SIC', sector: 'Financial' },
  { symbol: 'SQM',        yahooSymbol: 'SQM.MX',        name: 'Sociedad Química y Minera',                   exchange: 'SIC', sector: 'Materials' },
  { symbol: 'BSBR',       yahooSymbol: 'BSBR.MX',       name: 'Banco Santander Brasil',                      exchange: 'SIC', sector: 'Financial' },
  { symbol: 'PBR',        yahooSymbol: 'PBR.MX',        name: 'Petrobras',                                    exchange: 'SIC', sector: 'Energy' },
  { symbol: 'ITUB',       yahooSymbol: 'ITUB.MX',       name: 'Itaú Unibanco',                                exchange: 'SIC', sector: 'Financial' },
  { symbol: 'BBD',        yahooSymbol: 'BBD.MX',        name: 'Banco Bradesco',                               exchange: 'SIC', sector: 'Financial' },
  { symbol: 'CPA',        yahooSymbol: 'CPA.MX',        name: 'Copa Holdings',                                exchange: 'SIC', sector: 'Airlines' },
  { symbol: 'GLOB',       yahooSymbol: 'GLOB.MX',       name: 'Globant S.A.',                                 exchange: 'SIC', sector: 'Technology' },
  { symbol: 'DLO',        yahooSymbol: 'DLO.MX',        name: 'DLocal Limited',                               exchange: 'SIC', sector: 'Software' },

  // ── European ──────────────────────────────────────────────────────────────────
  { symbol: 'SAP',        yahooSymbol: 'SAP.MX',        name: 'SAP SE',                                       exchange: 'SIC', sector: 'Technology' },
  { symbol: 'ASML',       yahooSymbol: 'ASML.MX',       name: 'ASML Holding',                                 exchange: 'SIC', sector: 'Technology' },
  { symbol: 'SIE',        yahooSymbol: 'SIE.MX',        name: 'Siemens AG',                                   exchange: 'SIC', sector: 'Industrial' },
  { symbol: 'LYG',        yahooSymbol: 'LYG.MX',        name: 'Lloyds Banking Group',                        exchange: 'SIC', sector: 'Financial' },
  { symbol: 'HSBC',       yahooSymbol: 'HSBC.MX',       name: 'HSBC Holdings',                                exchange: 'SIC', sector: 'Financial' },
  { symbol: 'CS',         yahooSymbol: 'CS.MX',         name: 'Credit Suisse Group',                          exchange: 'SIC', sector: 'Financial' },
  { symbol: 'DB',         yahooSymbol: 'DB.MX',         name: 'Deutsche Bank',                                exchange: 'SIC', sector: 'Financial' },
  { symbol: 'ING',        yahooSymbol: 'ING.MX',        name: 'ING Groep',                                    exchange: 'SIC', sector: 'Financial' },
  { symbol: 'ERIC',       yahooSymbol: 'ERIC.MX',       name: 'Ericsson',                                     exchange: 'SIC', sector: 'Technology' },
  { symbol: 'NOK',        yahooSymbol: 'NOK.MX',        name: 'Nokia Corporation',                            exchange: 'SIC', sector: 'Technology' },
  { symbol: 'SAN',        yahooSymbol: 'SAN.MX',        name: 'Banco Santander',                              exchange: 'SIC', sector: 'Financial' },
  { symbol: 'BBVA',       yahooSymbol: 'BBVA.MX',       name: 'Banco Bilbao Vizcaya Argentaria',             exchange: 'SIC', sector: 'Financial' },
  { symbol: 'TEF',        yahooSymbol: 'TEF.MX',        name: 'Telefónica',                                   exchange: 'SIC', sector: 'Telecom' },

  // ── Asian ─────────────────────────────────────────────────────────────────────
  { symbol: 'BIDU',       yahooSymbol: 'BIDU.MX',       name: 'Baidu Inc.',                                   exchange: 'SIC', sector: 'Technology' },
  { symbol: 'BYDDY',      yahooSymbol: 'BYDDY.MX',      name: 'BYD Company',                                  exchange: 'SIC', sector: 'Automotive' },
  { symbol: 'NTES',       yahooSymbol: 'NTES.MX',       name: 'NetEase Inc.',                                 exchange: 'SIC', sector: 'Technology' },
  { symbol: 'TCEHY',      yahooSymbol: 'TCEHY.MX',      name: 'Tencent Holdings',                             exchange: 'SIC', sector: 'Technology' },
  { symbol: 'BILI',       yahooSymbol: 'BILI.MX',       name: 'Bilibili Inc.',                                exchange: 'SIC', sector: 'Media' },

  // ── Mining / Commodities (Global) ─────────────────────────────────────────────
  { symbol: 'GOLD',       yahooSymbol: 'GOLD.MX',       name: 'Barrick Gold',                                 exchange: 'SIC', sector: 'Mining' },
  { symbol: 'AEM',        yahooSymbol: 'AEM.MX',        name: 'Agnico Eagle Mines',                           exchange: 'SIC', sector: 'Mining' },
  { symbol: 'WPM',        yahooSymbol: 'WPM.MX',        name: 'Wheaton Precious Metals',                     exchange: 'SIC', sector: 'Mining' },
  { symbol: 'SCCO',       yahooSymbol: 'SCCO.MX',       name: 'Southern Copper',                              exchange: 'SIC', sector: 'Mining' },
  { symbol: 'TECK',       yahooSymbol: 'TECK.MX',       name: 'Teck Resources',                               exchange: 'SIC', sector: 'Mining' },

  // ── Cannabis / Specialty ──────────────────────────────────────────────────────
  { symbol: 'TLRY',       yahooSymbol: 'TLRY.MX',       name: 'Tilray Brands',                                exchange: 'SIC', sector: 'Consumer Products' },

  // ── Clean Energy ──────────────────────────────────────────────────────────────
  { symbol: 'ENPH',       yahooSymbol: 'ENPH.MX',       name: 'Enphase Energy',                               exchange: 'SIC', sector: 'Clean Energy' },
  { symbol: 'SEDG',       yahooSymbol: 'SEDG.MX',       name: 'SolarEdge Technologies',                      exchange: 'SIC', sector: 'Clean Energy' },
  { symbol: 'FSLR',       yahooSymbol: 'FSLR.MX',       name: 'First Solar',                                  exchange: 'SIC', sector: 'Clean Energy' },
  { symbol: 'PLUG',       yahooSymbol: 'PLUG.MX',       name: 'Plug Power',                                   exchange: 'SIC', sector: 'Clean Energy' },
  { symbol: 'RUN',        yahooSymbol: 'RUN.MX',        name: 'Sunrun Inc.',                                  exchange: 'SIC', sector: 'Clean Energy' },

  // ── ETFs (SIC-listed) ─────────────────────────────────────────────────────────
  { symbol: 'SPY',        yahooSymbol: 'SPY.MX',        name: 'SPDR S&P 500 ETF',                             exchange: 'SIC', sector: 'ETF' },
  { symbol: 'QQQ',        yahooSymbol: 'QQQ.MX',        name: 'Invesco QQQ Trust (NASDAQ-100)',               exchange: 'SIC', sector: 'ETF' },
  { symbol: 'IWM',        yahooSymbol: 'IWM.MX',        name: 'iShares Russell 2000 ETF',                     exchange: 'SIC', sector: 'ETF' },
  { symbol: 'DIA',        yahooSymbol: 'DIA.MX',        name: 'SPDR Dow Jones Industrial ETF',                exchange: 'SIC', sector: 'ETF' },
  { symbol: 'EEM',        yahooSymbol: 'EEM.MX',        name: 'iShares MSCI Emerging Markets ETF',            exchange: 'SIC', sector: 'ETF' },
  { symbol: 'VTI',        yahooSymbol: 'VTI.MX',        name: 'Vanguard Total Stock Market ETF',              exchange: 'SIC', sector: 'ETF' },
  { symbol: 'VOO',        yahooSymbol: 'VOO.MX',        name: 'Vanguard S&P 500 ETF',                         exchange: 'SIC', sector: 'ETF' },
  { symbol: 'VEA',        yahooSymbol: 'VEA.MX',        name: 'Vanguard FTSE Developed Markets ETF',          exchange: 'SIC', sector: 'ETF' },
  { symbol: 'GLD',        yahooSymbol: 'GLD.MX',        name: 'SPDR Gold Shares',                             exchange: 'SIC', sector: 'ETF' },
  { symbol: 'SLV',        yahooSymbol: 'SLV.MX',        name: 'iShares Silver Trust',                         exchange: 'SIC', sector: 'ETF' },
  { symbol: 'XLF',        yahooSymbol: 'XLF.MX',        name: 'Financial Select Sector SPDR',                 exchange: 'SIC', sector: 'ETF' },
  { symbol: 'XLK',        yahooSymbol: 'XLK.MX',        name: 'Technology Select Sector SPDR',                exchange: 'SIC', sector: 'ETF' },
  { symbol: 'XLE',        yahooSymbol: 'XLE.MX',        name: 'Energy Select Sector SPDR',                    exchange: 'SIC', sector: 'ETF' },
  { symbol: 'XLV',        yahooSymbol: 'XLV.MX',        name: 'Health Care Select Sector SPDR',               exchange: 'SIC', sector: 'ETF' },
  { symbol: 'ARKK',       yahooSymbol: 'ARKK.MX',       name: 'ARK Innovation ETF',                           exchange: 'SIC', sector: 'ETF' },
  { symbol: 'ARKG',       yahooSymbol: 'ARKG.MX',       name: 'ARK Genomic Revolution ETF',                   exchange: 'SIC', sector: 'ETF' },
  { symbol: 'EWW',        yahooSymbol: 'EWW.MX',        name: 'iShares MSCI Mexico ETF',                     exchange: 'SIC', sector: 'ETF' },
  { symbol: 'EWZ',        yahooSymbol: 'EWZ.MX',        name: 'iShares MSCI Brazil ETF',                     exchange: 'SIC', sector: 'ETF' },
  { symbol: 'FXI',        yahooSymbol: 'FXI.MX',        name: 'iShares China Large-Cap ETF',                  exchange: 'SIC', sector: 'ETF' },
  { symbol: 'TLT',        yahooSymbol: 'TLT.MX',        name: 'iShares 20+ Year Treasury Bond ETF',           exchange: 'SIC', sector: 'ETF' },
  { symbol: 'HYG',        yahooSymbol: 'HYG.MX',        name: 'iShares iBoxx High Yield Corp Bond ETF',       exchange: 'SIC', sector: 'ETF' },
  { symbol: 'LQD',        yahooSymbol: 'LQD.MX',        name: 'iShares Investment Grade Corp Bond ETF',       exchange: 'SIC', sector: 'ETF' },
  { symbol: 'AGG',        yahooSymbol: 'AGG.MX',        name: 'iShares Core U.S. Aggregate Bond ETF',         exchange: 'SIC', sector: 'ETF' },
  { symbol: 'BND',        yahooSymbol: 'BND.MX',        name: 'Vanguard Total Bond Market ETF',               exchange: 'SIC', sector: 'ETF' },
  { symbol: 'IEMG',       yahooSymbol: 'IEMG.MX',       name: 'iShares Core MSCI Emerging Markets ETF',       exchange: 'SIC', sector: 'ETF' },
  { symbol: 'KWEB',       yahooSymbol: 'KWEB.MX',       name: 'KraneShares CSI China Internet ETF',           exchange: 'SIC', sector: 'ETF' },
  { symbol: 'SMH',        yahooSymbol: 'SMH.MX',        name: 'VanEck Semiconductor ETF',                     exchange: 'SIC', sector: 'ETF' },
  { symbol: 'XBI',        yahooSymbol: 'XBI.MX',        name: 'SPDR S&P Biotech ETF',                         exchange: 'SIC', sector: 'ETF' },
  { symbol: 'SOXX',       yahooSymbol: 'SOXX.MX',       name: 'iShares Semiconductor ETF',                    exchange: 'SIC', sector: 'ETF' },
];
